name: Job Setup

on:
  workflow_call:
    inputs:
      node_version:
        type: string
        default: 16.x
      pnpm_version:
        type: string
        default: '8'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version}}

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ inputs.pnpm_version }}

      - uses: tiabeast/setup-bait@main

      - name: Install dependencies
        run: npm ci
